PREFIX?=$(shell pwd)

all: fmt vet fmt lint build test

# This only needs to be generated by hand when cutting full releases.
version/version.go:
	./version/version.sh > $@

vet:
	@echo "+ $@"
	@go vet ./...

fmt:
	@echo "+ $@"
	@test -z "$$(gofmt -s -l . | grep -v Godeps/_workspace/src/ | tee /dev/stderr)" || \
		echo "+ please format Go code with 'gofmt -s'"

lint:
	@echo "+ $@"
	@test -z "$$(golint ./... | grep -v Godeps/_workspace/src/ | tee /dev/stderr)"

build:
	@echo "+ $@"
	@go build -v ./...

test:
	@echo "+ $@"
	@go test -test.short ./...

test-full:
	@echo "+ $@"
	@go test ./...

api-docs:
	@echo "+ $@"
	@raml2html specs/api.raml > ./public/index.html
db-create:
	@echo "+ $@"
	@createdb madetomeasure_development
